
server:
  port: 8080
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        # Auth Service Route
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        # User Service Route
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**

        # Product Service Route
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
jwt:
  secret: 62160d85cc6cda363c383502805bfc3c68f2450bc61bf827824ab3c60a664790
  expiration: 86400000
